### PR TITLE
fix: explorer search broken in many ways

### LINKED ISSUE #503: Explorer search is broken
**Describe the bug**
Many search features in the explorer are broken. Changing the dates in advanced settings and pressing search does nothing. Limiting the number of responses doesn't actually change anything. Areas and text do work, however.

This is on develop.

### PR DESCRIPTION
**Pull request by jthistle**
- pagination settings now have an effect
- to make a new query the search button must be pressed, rather than just having
  a half-working automatic query system, which could also cause problems
- fixed an error with setting the page to 1 when there was no data

resolves #503

### CODE REVIEW

File: packages/explorer/src/components/Search/index.js [hunk 1]
```diff
@@ -356,8 +370,8 @@ class Search extends Component {
   /**
    * Getter for the search query string - strips empty fields.
    */
-  get queryString() {
-    const omitEmpty = _.pickBy(this.state.searchParams);
+  queryString(newParams) {
```
Comment (marxian) [inline packages/explorer/src/components/Search/index.js]: :+1:
