### PR TITLE
fix: align opening hours columns

### LINKED ISSUE #779: Radio buttons misaligned in Opening Hours.
Opening hours open/closed radio buttons are a bit higgledy-piggledy. 

Screen Shot 2020-06-04 at 20 00 31

Safari 13.1.1

### PR DESCRIPTION
**Pull request by falconx**
Fixes #779 

sm-2

opening-hours-md

### CODE REVIEW

File: src/components/EntryForm.js [hunk 1]
```diff
@@ -434,26 +433,29 @@ const EntryForm = ({ title, loo, center, children, ...props }) => {
 
           <Spacer mt={3} />
 
-          <ConditionalWrap
-            condition={!getValues('has-opening-times')}
-            wrap={(children) => <VisuallyHidden>{children}</VisuallyHidden>}
```
Comment (falconx) [inline src/components/EntryForm.js:439]: visually hidden wrapper meant that it was still possible to tab to these elements.
